<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\AgentDesk.Core\AgentDesk.Core.csproj" />
    <ProjectReference Include="..\AgentDesk.Server\AgentDesk.Server.csproj" />
  </ItemGroup>

</Project>
